### ISSUE TITLE
modshift enters an infinite loop for 205903217

### ISSUE THREAD

**Issue by fergalm** [barentsen/dave#1]
Congratulations Jeff, you are the recipient of the first DAVE bug report.

Which means you're also the guinea pig for using my data structures for debugging. Congratulations. You'll also be responsible for helping me debug my debugging functions.

Download the attached file and unzip it with `unzip clip-0205903217.zip`
[clip-0205903217.zip](https://github.com/barentsen/dave/files/57401/clip-0205903217.zip)

Open an ipython shell and type the following:

``` python
import dave.pipeline.pipeline as dpp
import dave.pipeline.clipboard as dpc

clip = dpc.loadClipboard('clip-0205903217.shelf')
```

If that fails, quit Ipython, type `conda install bsddb`, and try again.

You can see the error message and backtrace that modshift raised with

``` python
print clip.exception
print clip.backtrace
```

(You'll probably find the backtrace less useful because it's just telling you the problem happens in modshift).

To re-run the code to reproduce the bug do the following

``` python
clip.unsetException()     #Remove the exception so that the pipeline will run
clip = dpp.serveTask(clip)   #Reload the fits files were are deleted to save space

newClip = dpp.modshiftTask(clip)
```

This should fail with the same exception. When you have the code fixed, confirm that it runs by rerunning these two lines.

``` python
clip.unsetException()     #Remove the exception so that the pipeline will run
newClip = dpp.modshiftTask(clip)
```

What's happening the the pipeline is that I timeout on the modshift code if it runs for more than 10 seconds. The timeout is getting called for 6 of the 10 cases I ran, so it appears we still have a bit of a problem here.

**Comment by JeffLCoughlin** [comment]
I'm missing something before I can run import dave.pipeline.pipeline as dpp.  I added the base git directory to my PYTHONPATH. What am I missing?

**Comment by fergalm** [comment]
Add the directory above it. If your path is 
`/home/jeff/science/dave`
Add `/home/jeff/science` to your path.

**Comment by JeffLCoughlin** [comment]
_facepalm_ thanks, working now.

**Comment by JeffLCoughlin** [comment]
Had to rename clip-0205903217.shelf to clip-0205903217.shelf.dat, due to the following code:

----> 1 clip = dpc.loadClipboard('clip-0205903217.shelf')

/home/jeff/KeplerJob/DAVE/GIT/dave/pipeline/clipboard.pyc in loadClipboard(filename)
     13     sh = shelve.open(filename)
     14     if not os.path.exists(filename+".dat"):
---> 15         raise IOError("File not found: %s" %(filename))
     16 
     17     clip = sh['clip']

**Comment by fergalm** [comment]
$^&#$ I'd fixed that but hadn't checked it in. Depending on the backend used by shelve, the file is sometimes split into three parts for some reason, one of which is called .dat.

**Comment by JeffLCoughlin** [comment]
Getting the following error when executing "clip = dpp.serveTask()":

## In [13]: clip = dpp.serveTask()

AssertionError                            Traceback (most recent call last)
<ipython-input-13-d7ad028d7815> in <module>()
----> 1 clip = dpp.serveTask()

/home/jeff/KeplerJob/DAVE/GIT/dave/pipeline/task.pyc in wrapperForTask(_args, *_kwargs)
     78         Catches exceptions and either stores them or passes them to the debugger
     79         """
---> 80         assert(len(args) == 1)
     81         assert(len(kwargs) == 0)
     82 

If I feed it a 1 or 0  (e.g., clip = dpp.serveTask(0)) I get 

<ipython-input-16-feb74c06a034> in <module>()
----> 1 clip = dpp.serveTask(0)

/home/jeff/KeplerJob/DAVE/GIT/dave/pipeline/task.pyc in wrapperForTask(_args, *_kwargs)
     82 
     83         clip = args[0]
---> 84         if 'exception' in clip.keys():
     85             print "INFO: %s not run because exception previously raised" \
     86                 %(func.func_name)

AttributeError: 'int' object has no attribute 'keys'

**Comment by fergalm** [comment]
Try `clip = dpp.serveTask(clip)`

I've updated the original message to fix the error.

**Comment by JeffLCoughlin** [comment]
Okay, running:

clip = dpc.loadClipboard('clip-0205903217.shelf')
clip.unsetException()
clip = dpp.serveTask(clip)
newClip = dpp.modshiftTask(clip)

yields "INFO: modshiftTask not run because exception previously raised".

Running
clip.unsetException()
newClip = dpp.modshiftTask(clip)

clears the exception for reals. (So clip = dpp.serveTask(clip) is re-raising the exception?)

However now printing the exception and backtrace yields: 

In [28]: print clip.exception
'Required key serve not found while looking up serve.time'

In [29]: print clip.backtrace
Traceback (most recent call last):
  File "/home/jeff/KeplerJob/DAVE/GIT/dave/pipeline/task.py", line 105, in wrapperForTask
    clip = func(_args, *_kwargs)
  File "/home/jeff/KeplerJob/DAVE/GIT/dave/pipeline/pipeline.py", line 325, in modshiftTask
    time = clip['serve.time']
  File "/home/jeff/KeplerJob/DAVE/GIT/dave/pipeline/clipboard.py", line 86, in **getitem**
    return self.get(keyString)
  File "/home/jeff/KeplerJob/DAVE/GIT/dave/pipeline/clipboard.py", line 212, in get
    raise KeyError("Required key %s not found while looking up %s" %(k, keyString))
KeyError: 'Required key serve not found while looking up serve.time'

**Comment by fergalm** [comment]
Looks like serveTask is raising an exception. We should look to see what's going on. Do

``` python
clip.unsetException()
clip = dpp.serveTask(clip)
print clip.exception
```

My guess is that it's trying to cache a copy of the TPF and lightcurve file in ~/.mastio, and you need to create that directory. Eventually we'll have a setup script that will do that automatically so I don't keep forgetting to tell people about it.

**Comment by JeffLCoughlin** [comment]
Huh, it's running now. fetching the fits files. (I created ~/.mastio/k2/ before trying last time, odd.) Anyway, let's see how it goes here.

**Comment by JeffLCoughlin** [comment]
Now I'm getting:

could not convert string to float: is

which leads me to believe modshift.cpp is existing with error code 1 because the model is all flat.

  // Check to make sure model isn't all flat
  j=0;
  for(i=0;i<ndat;i++)
    if(data[i].model!=baseflux)
      j=1;
  if(j==0)
    {
    cout << "Model is all flat! Exiting..." << endl;
    exit(1);
    }

**Comment by fergalm** [comment]
Crap. I changed all your exit(0)'s to exit(1)'s so I could catch errors. But adding the timeout must be hiding that information. The test "Model is all flat!" is supposed to show up in the exception.

**Comment by fergalm** [comment]
Hang on, I just checked and it looks like I hadn't built the very latest version of your code. Let me run it see if the problem persists.

**Comment by JeffLCoughlin** [comment]
That could be it - I modified that block of code to allow for positive flux models. Before it would fail if the model only increased in flux.

**Comment by fergalm** [comment]
I'm now getting an error similar to yours

> Traceback (most recent call last):
>   File "/home/fergal/all/svns/dave/pipeline/task.py", line 105, in wrapperForTask
>     clip = func(_args, *_kwargs)
>   File "/home/fergal/all/svns/dave/pipeline/pipeline.py", line 346, in modshiftTask
>     period_days, epoch_bkjd)
>   File "/home/fergal/all/svns/dave/vetting/ModShift.py", line 113, in runModShift
>     mod_secdeptherr = float(info[15])
> IndexError: list index out of range

**Comment by JeffLCoughlin** [comment]
Hmm looks like I may not be parsing the output of modshift.cpp right. Can you print the results of 'modshiftcmdout' from ModShift.py?

**Comment by fergalm** [comment]
In the debugger

``` python
pdb> p info
['modshift', '21.6295493615', '8.4374846916', '3.3438952669', '6.6329628714', '22.0262000315', '13.8151483283', '4.6603155882', '3.6305597898', '0.0010945795', '0.2258713670', '0.3800031230', '0.5574143646', '0.0046831270', '0.0005550383']

pdb> len(info)
15
```

So it looks like there's one fewer tokens being returned than expected.

**Comment by JeffLCoughlin** [comment]
Found it - I left out printing sig_fa_2 from modshift.cpp. Okay, fixed now, and pushed to git. Try pulling and re-compiling modshift.cpp and give it a go.

**Comment by JeffLCoughlin** [comment]
Er guess I will too on my side.

**Comment by fergalm** [comment]
Yep, that fixed it. Code now runs to completion. I'll run it on the rest of the set, and open more issues if it fails for some other reason.

**Comment by JeffLCoughlin** [comment]
Yay!  Glad we could debug the debugging to debug the code!

**Comment by fergalm** [comment]
That was kinda fun. Hopefully this approach will make it easier to fix problems when they crop up.

**Comment by JeffLCoughlin** [comment]
Yea that is a really great way to do it!
