### ISSUE TITLE
BLS finding very short transit duration

### ISSUE THREAD

**Issue by fergalm** [barentsen/dave#3]
I'm looking at 206181269 in C3, which is a white dwarf with no strong signals. 
BLS is finding the strongest peak at .55 days with a transit duration of 0.046 hours. (My code takes the return value for duration from BLS and assumes it's days. If that's wrong let me know).

The short transit duration causes a problem for modshift because the model transit signal created by the trapezoid fit contains all zeros. modshift complains that it can't fit that, and raises an exception.

What's the best thing to do here? Should BLS be forced to return a minimum transit duration, or should the pipeline check for this problem and do something about it?

**Comment by mrtommyb** [comment]
The solution might be to force it to return a longer transit duration.

**Comment by fergalm** [comment]
The problem was that python-bls inputs a range of fractional transit durations  (e.g 1% of period) instead of actual transit duration (e.g 6 hours). When searching a wide period range this results in very short and very long absolute transit durations being searched.

We've replaced python-bls with fbls, which searches absolute transit durations so this problem has been resolved.
