### ISSUE TITLE
BLS returns negative depth which is not expected in trapezoid fit

### ISSUE THREAD

**Issue by christopherburke** [barentsen/dave#5]
BLS can return a negative depth.  This will raise a value error exception in the trapezoid fit.  How do we want to handle such cases?

**Comment by fergalm** [comment]
Tom, I've seen negative depths out of BLS a couple of times too. Do you know what's going on?

**Comment by mrtommyb** [comment]
is it due to my pseudo-normalization?

**Comment by fergalm** [comment]
We're now using fbls instead of python_bls, so this bug is overcome by events.
