### ISSUE TITLE
'Required key modshift not found while looking up modshift'

### ISSUE THREAD

**Issue by JeffLCoughlin** [barentsen/dave#6]
I can't figure this one out - it's preventing me from being able to do a full run and look in to Chris' modshift issue.

main.runOne(206103150,cfg)
'Required key modshift not found while looking up modshift'

> /home/jeff/KeplerJob/DAVE/GIT/dave/pipeline/clipboard.py(229)get()
> -> raise KeyError("Required key %s not found while looking up %s" %(k, keyString))

**Comment by JeffLCoughlin** [comment]
KeyError                                  Traceback (most recent call last)
<ipython-input-6-b6a7a4fb9a23> in <module>()
----> 1 main.runOne(206103150,cfg)

/home/jeff/KeplerJob/DAVE/GIT/dave/pipeline/main.pyc in runOne(k2id, config)
     77     for t in taskList:
     78         f = eval(t)
---> 79         clip = f(clip)
     80 
     81     return clip

/home/jeff/KeplerJob/DAVE/GIT/dave/pipeline/task.pyc in wrapperForTask(_args, *_kwargs)
    112                 print e
    113                 pdb.post_mortem(sys.exc_info()[2])
--> 114                 raise e
    115             else:
    116                 clip['exception'] = e

KeyError: 'Required key modshift not found while looking up modshift'

**Comment by fergalm** [comment]
Jeff sent me the following backtrace

> /home/jeff/KeplerJob/DAVE/GIT/dave/pipeline/clipboard.py(229)get()
> -> raise KeyError("Required key %s not found while looking up %s" %(k, keyString))
> (Pdb) bt
>   /home/jeff/KeplerJob/DAVE/GIT/dave/pipeline/task.py(105)wrapperForTask()
> -> clip = func(_args, *_kwargs)
>   /home/jeff/KeplerJob/DAVE/GIT/dave/pipeline/pipeline.py(638)dispositionTask()
> -> #Data on which to make a decision
>   /home/jeff/KeplerJob/DAVE/GIT/dave/pipeline/clipboard.py(92)**getitem**()
> -> return self.get(keyString)
> /home/jeff/KeplerJob/DAVE/GIT/dave/pipeline/clipboard.py(229)get()
> -> raise KeyError("Required key %s not found while looking up %s" %(k, keyString))

The offending line seems to be in dispositionTask

> modshiftDict = clip['modshift']

This is just loading the result of the modshiftTask from the clipboard.

The last lines of modshiftTask() should look like this

```
    out = ModShift.runModShift(time[~fl], flux[~fl], model, basename, \
        objectname, period_days, epoch_bkjd)

    clip['modshift'] = out
```

My guess is this is what you've changed.

**Comment by JeffLCoughlin** [comment]
Hmm, my lines are identical to what you posted. I haven't touched any of this recently. I just did a git pull and tried to run the pipeline and got this error.  Maybe I'll just do a fresh pull from git and try from scratch.

**Comment by JeffLCoughlin** [comment]
Doing a fresh git clone, a 'make' in vetting, and:

from dave.pipeline import main
cfg=main.loadMyConfiguration()
clip = main.runOne(206103150,cfg)

still results in the same error.

'Required key modshift not found while looking up modshift'
> /home/jeff/KeplerJob/DAVE/GIT/dave/pipeline/clipboard.py(229)get()
-> raise KeyError("Required key %s not found while looking up %s" %(k, keyString))
(Pdb) bt
  /home/jeff/KeplerJob/DAVE/GIT/dave/pipeline/task.py(105)wrapperForTask()
-> clip = func(*args, **kwargs)
  /home/jeff/KeplerJob/DAVE/GIT/dave/pipeline/pipeline.py(640)dispositionTask()
-> modshiftDict = clip['modshift']
  /home/jeff/KeplerJob/DAVE/GIT/dave/pipeline/clipboard.py(92)__getitem__()
-> return self.get(keyString)
> /home/jeff/KeplerJob/DAVE/GIT/dave/pipeline/clipboard.py(229)get()
-> raise KeyError("Required key %s not found while looking up %s" %(k, keyString))

**Comment by JeffLCoughlin** [comment]
Doing a fresh git clone, running 'make' in vetting, and then 

from dave.pipeline import main
cfg=main.loadMyConfiguration()
clip = main.runOne(206103150,cfg)

still results in the error.

'Required key modshift not found while looking up modshift'

> /home/jeff/KeplerJob/DAVE/GIT2/dave/pipeline/clipboard.py(229)get()
> -> raise KeyError("Required key %s not found while looking up %s" %(k, keyString))
> (Pdb) bt
>   /home/jeff/KeplerJob/DAVE/GIT2/dave/pipeline/task.py(105)wrapperForTask()
> -> clip = func(_args, *_kwargs)
>   /home/jeff/KeplerJob/DAVE/GIT2/dave/pipeline/pipeline.py(640)dispositionTask()
> -> modshiftDict = clip['modshift']
>   /home/jeff/KeplerJob/DAVE/GIT2/dave/pipeline/clipboard.py(92)**getitem**()
> -> return self.get(keyString)
> /home/jeff/KeplerJob/DAVE/GIT2/dave/pipeline/clipboard.py(229)get()
> -> raise KeyError("Required key %s not found while looking up %s" %(k, keyString))

**Comment by mustaric** [comment]
Jeff,
   What does your task list look like? Maybe you are not running the vetting task?  There some problems with getting a full list in there a while back.
Susan

**Comment by mustaric** [comment]
Yup. It looks like, if you are running the default from a true git clone, then dpp.modshiftTask isn't listed.

**Comment by mustaric** [comment]
I pushed a change to main.py that has the lists of tasks I use.

**Comment by JeffLCoughlin** [comment]
Looks like you commented out line 39 in the task list, but needed 39-43. I'll fix and push.

**Comment by JeffLCoughlin** [comment]
Okay working now. Thanks all.
