### ISSUE TITLE
Detrend task fails error "setting an array element with a sequence"

### ISSUE THREAD

**Issue by fergalm** [barentsen/dave#8]
In the recent C6 run (on /soc/nfs/so-nfs/dave/c6-v2), EPIC 212293125 failed with a value error. Here's the traceback

Traceback (most recent call last):
  File "/home/fergal/all/svns/dave/pipeline/task.py", line 105, in wrapperForTask
    clip = func(_args, *_kwargs)
  File "/home/fergal/all/svns/dave/pipeline/pipeline.py", line 291, in detrendDataTask
    detrendedFlux[cad] = flux[cad] - fillval[fillval != 0]
  File "/home/fergal/all/svns/dave/fileio/nca.py", line 104, in **setitem**
    np.ndarray.**setitem**(self, key, value)
ValueError: setting an array element with a sequence.

About 130 of the ~4000 targets looked at raised this exception.

Tom, this looks like your code, can you take a look? Issue #1 contains advice on reading in a clip and using it for debugging.

**Comment by mrtommyb** [comment]
Ok, I'm investigating. I think it's pretty clear what's going on. 
Do you have an example of where everything works well

**Comment by fergalm** [comment]
There's about 130 that fail for this reason out of 4000, so it works well most of the time. Try 212,756,297 as a pretty example of one that ran to completion.

**Comment by mrtommyb** [comment]
Can you push the as run version to github. I'm not seeing some of the changes

**Comment by mrtommyb** [comment]
e9370ca fixes this issue

**Comment by fergalm** [comment]
As run is pushed.

**Comment by mrtommyb** [comment]
You should be able to just rerun those 130 targets. This bug should not effect the other targets.
