### ISSUE TITLE
File I/O tries to get C6 target from C3

### ISSUE THREAD

**Issue by JeffLCoughlin** [barentsen/dave#9]
I went to run one of our C6 PCs (212394689), after doing a git pull just now, via the normal

from dave.pipeline import main
cfg=main.loadMyConfiguration()
clip = main.runOne(212394689,cfg)

I get the error:

File http://archive.stsci.edu/pub/k2/target_pixel_files/c3/212300000/94000/ktwo212394689-c03_lpd-targ.fits.gz previously returned 404

> /home/jeff/KeplerJob/DAVE/GIT/dave/fileio/mastio.py(35)getData()
> -> raise IOError("File %s previously returned 404" %(remoteUrl))

Looks like it's trying to pull from C3 instead of C6 at MAST. I poked around a bit but couldn't quite figure out where it was getting campaign information from.

More debug:
 31             if not forceDownload:
 32                 if os.path.exists(localUrl):
 33                     isEmpty = os.stat(localUrl)[6]==0
 34                     if isEmpty:
 35  ->                     raise IOError("File %s previously returned 404" %(remoteUrl))

**Comment by fergalm** [comment]
Try

``` python
from dave.pipeline import main
cfg=main.loadMyConfiguration()
cfg['campaign'] = 3
clip = main.runOne(212394689,cfg)
```

Storing the campaign number in the clip is a bit cludgy, and I'm open to suggestions for improvement. Inferring the campaign from the epic is a non-runner because later fields overlap and you it's possible to observe the same epic in two campaigns.

**Comment by JeffLCoughlin** [comment]
yea nice, cfg['campaign'] = 6 works. Thanks.

**Comment by mrtommyb** [comment]
Do you want me to write an EPIC to campaign converter? This would make the
default campaign number redundant.

**Comment by fergalm** [comment]
What would it do if the same epic is observed in two campaigns?

**Comment by mrtommyb** [comment]
Freak out.
![Freak out](http://i.giphy.com/52HjuHsfVO69q.gif)

**Comment by fergalm** [comment]
Not the worst thing [it could do: ](https://www.youtube.com/watch?v=h1qQ1SKNlgY)

**Comment by JeffLCoughlin** [comment]
I need to remember that gif.

I'd say if you did write one Tom, for now just select the lowest-number campaign. If there becomes a significant number of targets that we want to search in the future, we can write a stitcher to combine multiple campaigns.

**Comment by mustaric** [comment]
In general, I don't think this is a high priority problem to solve. For the once off cases, it would be great. But when running thousands of these, they will all be from the same campaign and we will remember to set the value in the clip.  Maybe a better warning about why we are not finding data would be helpful.  
Can serveTask handle reading in more than one campaign's worth of data?
